formatter: "markdown table"

version: "0.16"
header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: ""

sections:
  hide: []
  show: []

content: |-
  {{ .Requirements }}

  ## Usage
  해당 모듈의 기본 사용법은 아래와 같습니다

  ```hcl
  module "example" {
  {{"\t"}}source = "<module-path>"

  {{- if .Module.RequiredInputs }}
    {{"\n\t"}}# Required variables
    {{- range .Module.RequiredInputs }}
      {{"\t"}}{{ .Name }} = {{ .GetValue }}
    {{- end }}
  {{- end }}

  {{- if .Module.OptionalInputs }}
    {{"\n\t"}}# Optional variables
    {{- range .Module.OptionalInputs }}
      {{"\t"}}{{ .Name }} = {{ .GetValue | printf "%s" }}
    {{- end }}
  {{- end }}
  }
  ```
  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
      <!-- BEGIN_AUTOMATED_TF_DOCS_BLOCK -->
      {{ .Content }}
      <!-- END_AUTOMATED_TF_DOCS_BLOCK -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true